"""
The real, evidence-grounded MCP runtime fault taxonomy.

Source: Owotogbe, Kumara, van den Heuvel, Tamburri, Iannillo, Natella (2026),
"A Taxonomy of Runtime Faults in Model Context Protocol Servers", arXiv:2606.05339.
837 confirmed fault threads across 473 MCP repos, validated by 55 real MCP
server developers. See the project's architecture doc for full citation and caveats.
"""

TAXONOMY = [
    {"category": "Base Protocol", "subcategory": "Message Structure",
     "text": "Missing or malformed required JSON-RPC 2.0 fields such as id, method, params, result, or error, breaking request response conformance.",
     "confirmed_pct": 60, "severity": {"minor": 61, "major": 21, "critical": 18}, "effort": {"low": 52, "medium": 33, "high": 15}},
    {"category": "Base Protocol", "subcategory": "Message Semantics",
     "text": "Well formed JSON-RPC messages whose meaning is wrong, mismatched identifiers across related events, or failures reported as HTTP codes instead of JSON-RPC error objects.",
     "confirmed_pct": 49, "severity": {"minor": 44, "major": 37, "critical": 19}, "effort": {"low": 22, "medium": 59, "high": 19}},
    {"category": "Transport Layer", "subcategory": "Stdio Transport",
     "text": "Non protocol data written to stdout corrupts the JSON-RPC message stream over the stdio transport.",
     "confirmed_pct": 47, "severity": {"minor": 42, "major": 50, "critical": 8}, "effort": {"low": 31, "medium": 54, "high": 15}},
    {"category": "Transport Layer", "subcategory": "Streamable HTTP",
     "text": "Faulty handling of HTTP requests, session identifiers, or server sent event streams under the Streamable HTTP transport binding.",
     "confirmed_pct": 36, "severity": {"minor": 39, "major": 33, "critical": 28}, "effort": {"low": 26, "medium": 53, "high": 21}},
    {"category": "Session Lifecycle", "subcategory": "Initialization",
     "text": "Faults during session setup, protocol version mismatches, races during capability negotiation, use of uninitialized state, missing initialized notifications.",
     "confirmed_pct": 36, "severity": {"minor": 75, "major": 15, "critical": 10}, "effort": {"low": 45, "medium": 30, "high": 25}},
    {"category": "Session Lifecycle", "subcategory": "State Transition",
     "text": "Faults in the control flow of an already active session, missing awaits, sync calls in async contexts, missing loop stop conditions, requests handled pre initialization.",
     "confirmed_pct": 47, "severity": {"minor": 23, "major": 62, "critical": 15}, "effort": {"low": 27, "medium": 38, "high": 35}},
    {"category": "Session Lifecycle", "subcategory": "Termination",
     "text": "Improper shutdown ordering, resources not released on termination, or input streams left open on exit.",
     "confirmed_pct": 25, "severity": {"minor": 29, "major": 50, "critical": 21}, "effort": {"low": 29, "medium": 50, "high": 21}},
    {"category": "State & Configuration", "subcategory": "Configuration Handling",
     "text": "Server level configuration flags accepted but not enforced, or invalid parameter values silently producing undocumented behavior.",
     "confirmed_pct": 33, "severity": {"minor": 61, "major": 28, "critical": 11}, "effort": {"low": 50, "medium": 33, "high": 17}},
    {"category": "State & Configuration", "subcategory": "Session State",
     "text": "Stale or reused session identifiers, missing session id headers, or identifiers stripped by middleware, breaking request correlation.",
     "confirmed_pct": 36, "severity": {"minor": 50, "major": 40, "critical": 10}, "effort": {"low": 40, "medium": 35, "high": 25}},
    {"category": "State & Configuration", "subcategory": "Resource State",
     "text": "Server managed resource state that is stale or fails to persist across operations.",
     "confirmed_pct": 31, "severity": {"minor": 53, "major": 35, "critical": 12}, "effort": {"low": 38, "medium": 56, "high": 6}},
    {"category": "Tool", "subcategory": "Tool Identification",
     "text": "Tools missing from the capabilities declaration, or invalid input output schema specifications, making them undiscoverable or uncallable.",
     "confirmed_pct": 42, "severity": {"minor": 57, "major": 35, "critical": 9}, "effort": {"low": 52, "medium": 43, "high": 4}},
    {"category": "Tool", "subcategory": "Tool Execution",
     "text": "Faults in tool handlers after declaration, input type mismatches, non terminating execution, missing input validation, runtime errors not surfaced as JSON-RPC errors.",
     "confirmed_pct": 73, "severity": {"minor": 42, "major": 52, "critical": 5}, "effort": {"low": 35, "medium": 55, "high": 10}},
    {"category": "Tool", "subcategory": "Tool Result Propagation",
     "text": "Faults after tool execution completes but before the result is correctly returned, missing payloads, wrong content structure, false success despite an underlying failure.",
     "confirmed_pct": 67, "severity": {"minor": 44, "major": 47, "critical": 8}, "effort": {"low": 47, "medium": 33, "high": 19}},
    {"category": "Resource", "subcategory": "Resource Identification",
     "text": "Invalid URI structures or non resolvable resource paths preventing clients from reading declared resources.",
     "confirmed_pct": 25, "severity": {"minor": 64, "major": 14, "critical": 21}, "effort": {"low": 62, "medium": 23, "high": 15}},
    {"category": "Resource", "subcategory": "Resource Synchronization",
     "text": "Resource state that falls out of sync between server and client after updates, notifications, or concurrent access.",
     "confirmed_pct": 29, "severity": {"minor": 44, "major": 31, "critical": 25}, "effort": {"low": 31, "medium": 44, "high": 25}},
    {"category": "Prompt", "subcategory": "Prompt Identification",
     "text": "Faults in prompt lookup and resolution, unknown prompt names mishandled, or prompt related errors mapped incorrectly.",
     "confirmed_pct": 47, "severity": {"minor": 62, "major": 19, "critical": 19}, "effort": {"low": 65, "medium": 19, "high": 15}},
    {"category": "Prompt", "subcategory": "Prompt Argument Handling",
     "text": "Arguments supplied to a prompt violate its declared input schema, or values are substituted incorrectly.",
     "confirmed_pct": 36, "severity": {"minor": 47, "major": 32, "critical": 21}, "effort": {"low": 40, "medium": 40, "high": 20}},
    {"category": "Model Provider Integration", "subcategory": "Model Identification",
     "text": "Invalid model identifiers, unsupported sampling parameters, or attempts to invoke a model not available via the configured provider.",
     "confirmed_pct": 25, "severity": {"minor": 50, "major": 29, "critical": 21}, "effort": {"low": 50, "medium": 29, "high": 21}},
    {"category": "Model Provider Integration", "subcategory": "Provider Integration",
     "text": "Provider unavailability, incomplete provider initialization, or failure to list available models during capability negotiation.",
     "confirmed_pct": 51, "severity": {"minor": 32, "major": 54, "critical": 14}, "effort": {"low": 36, "medium": 43, "high": 21}},
    {"category": "Data & Schema", "subcategory": "Schema Compatibility",
     "text": "Emitted content that does not conform to the declared JSON Schema for a capability, missing required properties or structural deviation.",
     "confirmed_pct": 69, "severity": {"minor": 58, "major": 32, "critical": 11}, "effort": {"low": 61, "medium": 21, "high": 18}},
    {"category": "Data & Schema", "subcategory": "Data Type and Structure",
     "text": "Payloads that satisfy the declared schema but carry values such as unexpected nulls that break downstream implementation assumptions.",
     "confirmed_pct": 56, "severity": {"minor": 65, "major": 23, "critical": 13}, "effort": {"low": 61, "medium": 26, "high": 13}},
    {"category": "Data & Schema", "subcategory": "Output Representation",
     "text": "Syntactically valid JSON that does not conform to the expected structured output representation, hindering correct interpretation.",
     "confirmed_pct": None, "severity": {}, "effort": {}},
    {"category": "Security", "subcategory": "Authentication",
     "text": "Missing Authorization headers, expired bearer tokens, or malformed token values that block proper client authentication.",
     "confirmed_pct": 55, "severity": {"minor": 47, "major": 40, "critical": 13}, "effort": {"low": 41, "medium": 38, "high": 21}},
    {"category": "Security", "subcategory": "Token Validation",
     "text": "Tokens present but not correctly verified against expected claims such as audience mismatch, or forwarded upstream unverified.",
     "confirmed_pct": 42, "severity": {"minor": 48, "major": 43, "critical": 9}, "effort": {"low": 36, "medium": 32, "high": 32}},
    {"category": "Security", "subcategory": "Authorization",
     "text": "Missing access control checks after authentication, capabilities or tools invoked without verifying caller permissions.",
     "confirmed_pct": 40, "severity": {"minor": 27, "major": 55, "critical": 18}, "effort": {"low": 24, "medium": 43, "high": 33}},
    {"category": "Timeout & Cancellation", "subcategory": "Operation Timeout",
     "text": "Fixed timeout thresholds too short for the actual workload such as long running or streaming tool calls, terminating operations prematurely.",
     "confirmed_pct": 44, "severity": {"minor": 42, "major": 42, "critical": 17}, "effort": {"low": 38, "medium": 42, "high": 21}},
    {"category": "Timeout & Cancellation", "subcategory": "Operation Cancellation",
     "text": "Cancellation requests that fail to propagate, or stream termination signals ignored by execution handlers.",
     "confirmed_pct": 29, "severity": {"minor": 44, "major": 50, "critical": 6}, "effort": {"low": 62, "medium": 19, "high": 19}},
]


def dominant(dist: dict) -> str | None:
    if not dist:
        return None
    return max(dist.items(), key=lambda kv: kv[1])[0]
